# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 14:32
from __future__ import unicode_literals

import devices.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Device ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Devices IP-address:')),
                ('name', models.CharField(blank=True, editable=False, max_length=63, verbose_name='Device name:')),
                ('fqdn', models.CharField(blank=True, max_length=63, verbose_name='Device FQDN:')),
                ('platform', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Device hardware model:')),
                ('software_version', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Device software version:')),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Device S/N:')),
                ('up_time', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Device ucptime:')),
                ('last_checked_time', models.DateTimeField(editable=False, verbose_name='Device last checked time:')),
                ('last_checked_status', models.CharField(editable=False, max_length=4, verbose_name='Device last checked status (UP/DOWN):')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_path', models.FileField(upload_to=devices.models.device_config_path)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
    ]
