# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='devices.Parent')),
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='Devices management IP-address:')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Device description')),
                ('poll_flag', models.BooleanField(default=True, verbose_name='True for regularly polling this device')),
                ('hostname', models.CharField(default='unknown', editable=False, max_length=63, verbose_name='Device name:')),
                ('fqdn', models.CharField(default='unknown', max_length=63, verbose_name='Device FQDN:')),
                ('model', models.CharField(default='unknown', editable=False, max_length=50, verbose_name='Device hardware model:')),
                ('version', models.CharField(default='unknown', editable=False, max_length=50, verbose_name='Device software version:')),
                ('serialnumber', models.CharField(default='unknown', editable=False, max_length=50, verbose_name='Device S/N:')),
                ('up_time', models.CharField(default='unknown', editable=False, max_length=50, verbose_name='Device uptime:')),
                ('two_re', models.BooleanField(default=False, editable=False, verbose_name='Device has 2 RE (True/False)')),
                ('last_checked_time', models.DateTimeField(auto_now=True, verbose_name='Device last checked time:')),
                ('last_checked_status', models.BooleanField(default=False, editable=False, verbose_name='True for UP, False for DOWN:')),
            ],
            bases=('devices.parent',),
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Parent')),
                ('instance_name', models.CharField(editable=False, max_length=100)),
                ('instance_type', models.CharField(blank=True, editable=False, max_length=30)),
                ('router_id', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('instance_state', models.CharField(blank=True, editable=False, max_length=30)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            bases=('devices.parent',),
        ),
        migrations.CreateModel(
            name='InstanceArpTable',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Parent')),
                ('mac_address', models.CharField(editable=False, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('interface_name', models.CharField(blank=True, editable=False, max_length=100)),
                ('hostname', models.CharField(blank=True, editable=False, max_length=100)),
                ('vpn', models.CharField(blank=True, editable=False, max_length=100)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('related_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInstance')),
            ],
            bases=('devices.parent',),
        ),
        migrations.CreateModel(
            name='InstanceLogInterface',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Parent')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('address_family_name', models.CharField(blank=True, editable=False, max_length=50)),
                ('encapsulation', models.CharField(blank=True, editable=False, max_length=20)),
                ('mtu', models.CharField(blank=True, editable=False, max_length=20)),
                ('ifa_local', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('ifa_prefix', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('input_packets', models.IntegerField(blank=True, editable=False, null=True)),
                ('output_packets', models.IntegerField(blank=True, editable=False, null=True)),
                ('filter_information', models.CharField(blank=True, editable=False, max_length=100)),
                ('logical_interface_zone_name', models.CharField(blank=True, editable=False, max_length=100)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('related_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInstance')),
            ],
            bases=('devices.parent',),
        ),
        migrations.CreateModel(
            name='InstancePhyInterface',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Parent')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('admin_status', models.BooleanField(default=False, editable=False, verbose_name='True for UP, False for DOWN:')),
                ('oper_status', models.BooleanField(default=False, editable=False, verbose_name='True for UP, False for DOWN:')),
                ('speed', models.CharField(blank=True, editable=False, max_length=20)),
                ('mtu', models.CharField(blank=True, editable=False, max_length=20)),
                ('link_mode', models.CharField(blank=True, editable=False, max_length=20)),
                ('if_auto_negotiation', models.CharField(default=False, editable=False, max_length=20)),
                ('link_level_type', models.CharField(blank=True, editable=False, max_length=20)),
                ('current_physical_address', models.CharField(blank=True, editable=False, max_length=34)),
                ('hardware_physical_address', models.CharField(blank=True, editable=False, max_length=34)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('related_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInstance')),
            ],
            bases=('devices.parent',),
        ),
        migrations.CreateModel(
            name='InstanceRIB',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Parent')),
                ('table_name', models.CharField(editable=False, max_length=100)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('related_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInstance')),
            ],
            bases=('devices.parent',),
        ),
        migrations.CreateModel(
            name='InstanceRouteTable',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Parent')),
                ('rt_destination_ip', models.GenericIPAddressField(editable=False)),
                ('rt_destination_prefix', models.PositiveSmallIntegerField(editable=False)),
                ('active_tag', models.BooleanField(editable=False, verbose_name='True for *, False for other:')),
                ('protocol_name', models.CharField(blank=True, editable=False, max_length=20)),
                ('preference', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('nh_local_interface', models.CharField(blank=True, editable=False, max_length=100)),
                ('nh_table', models.CharField(blank=True, editable=False, max_length=100)),
                ('nh_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('via', models.CharField(blank=True, editable=False, max_length=100)),
                ('related_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('related_rib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.InstanceRIB')),
            ],
            bases=('devices.parent',),
        ),
        migrations.AddField(
            model_name='instanceloginterface',
            name='related_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.InstancePhyInterface'),
        ),
        migrations.AlterUniqueTogether(
            name='instanceroutetable',
            unique_together=set([('related_device', 'related_rib', 'rt_destination_ip', 'rt_destination_prefix')]),
        ),
        migrations.AlterUniqueTogether(
            name='instancerib',
            unique_together=set([('related_device', 'related_instance', 'table_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instancephyinterface',
            unique_together=set([('related_device', 'related_instance', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instanceloginterface',
            unique_together=set([('related_device', 'related_instance', 'related_interface', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instancearptable',
            unique_together=set([('related_device', 'related_instance', 'mac_address')]),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinstance',
            unique_together=set([('related_device', 'instance_name')]),
        ),
    ]
