# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_checked_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Device last checked time:'),
        ),
    ]
